### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by cartal** [theislab/scgen#14]
Hi guys, 

I had to upgrade my `tensorflow` to re-install `diffxpy` and this seems to have broken my `scGen`: I've got the `AttributeError:` module 'tensorflow' has no attribute 'placeholder'`. 

I'm trying to find a workaround this, but it seems that it's something that `scGen` will have to fix at some point? Do you have any recommendations? 

Thanks in advance!

**Comment by cartal** [comment]
The solution provided by the Tensorflow team on their website: 

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

```
doesn't seem to work either

**Comment by Kaarthic29** [comment]
Hi,

Even I face the same AttributeError: module 'tensorflow' has no attribute 'placeholder' issue with tensorflow version 2.0

**Comment by Kaarthic29** [comment]
Thanks @M0hammadL , as of now i have used tf.compat.v1 to solve that placeholder error in tf v2.0

**Comment by LaylaUJ** [comment]
AttributeError: module 'tensorflow' has no attribute 'placeholder'
 can any one please tell me how to solve this error message

**Comment by Kiran995** [comment]
Tensorflow 2.0 does not seems have placeholder(), .reset_default_graph(). 
You can find more information here: [(https://www.tensorflow.org/guide/effective_tf2)]

**Comment by mikeyEcology** [comment]
I solved this and several other incompatibilities in my code by going back to tensorflow version 1:
`pip install tensorflow==1.4`

**Comment by Djokovicxw** [comment]
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
```
works.
I am using Python 3.7 and tensorflow 2.0.

**Comment by botbark** [comment]
This error may come if you have installed TensorFlow 2.0 and want to run code that is not compatible with TensorFlow 2.0

For example if you are trying to run below code, you will get the above error.
Please check the below post.

https://botbark.com/2019/12/18/attributeerror-module-tensorflow-has-no-attribute-placeholder-tensorflow-2-0/

**Comment by kaungsoethar** [comment]
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> works.
> I am using Python 3.7 and tensorflow 2.0.

It works well
Thank you ^_^

**Comment by yannis1962** [comment]
I re-installed tensorflow==1.15.2 and it worked (otherwise rasa-nlu wouldn't work)

**Comment by rajesh0816** [comment]
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> works.
> I am using Python 3.7 and tensorflow 2.0.

yeah it is working now

**Comment by shariefimran** [comment]
> > ```
> > import tensorflow.compat.v1 as tf
> > tf.disable_v2_behavior() 
> > ```
> > 
> > 
> > works.
> > I am using Python 3.7 and tensorflow 2.0.
> 
> yeah it is working now

for me its not working

**Comment by Gennaro-Farina** [comment]
> 
> 
> > > ```
> > > import tensorflow.compat.v1 as tf
> > > tf.disable_v2_behavior() 
> > > ```
> > > 
> > > 
> > > works.
> > > I am using Python 3.7 and tensorflow 2.0.
> > 
> > 
> > yeah it is working now
> 
> for me its not working

Hello sharifimran, for me what worked was to reinstall TF + Keras version I use. Try this combination:
`python  -m pip install Keras==2.3.1 tensorflow==2.1.0`

**Comment by moschjoon** [comment]
just remove the current version of tensorflow (using command: conda remove tensorflow), then install 1.15.0 using command: conda install tensorflow=1.15.0..it works

**Comment by deepgupta06** [comment]
The same problem was happening to me...

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

it works..

**Comment by RahulKamma0369** [comment]
> The solution provided by the Tensorflow team on their website:
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> doesn't seem to work either

well it worked for me

**Comment by RahulKamma0369** [comment]
the error is because we are using tensorflow version 2 and the command is from version 1 so if we use  tf.compat.v1.summary.(method_name) it'll work

**Comment by sakshijain032** [comment]
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

It worked for me too. I was getting this error from this file
site-packages\keras\backend\tensorflow_backend.py 
I used this code over there.

**Comment by parva-jain** [comment]
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

It is working for me but the thing is it is affecting other parts of my code so is there any solution within version 2

**Comment by sakshijain032** [comment]
May I know what it's affecting

**Comment by parva-jain** [comment]
what these couple of line of codes does is disabling the version 2 of
tensorflow but I'm using AdamOptimizer which have different syntax in
different versions and executing those couple of line is affecting the
version 2 syntax of AdamOptimizer.....I may not be so clear as I'm new
tensorflow user but any help would be appreciated

**Comment by cu2uyash** [comment]
pip install tensorflow==1.4 will work as it has placeholder attribute

**Comment by Gooogr** [comment]
If you use Keras try change your import from keras.name_of_class to tensorflow.keras.name_of_class

**Comment by qinchaofeng** [comment]
> The solution provided by the Tensorflow team on their website:
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> doesn't seem to work either

I was using tf(2.0.0-alpha0),python(Python 3.6.4) and it worked for me

**Comment by amansani** [comment]
> just remove the current version of tensorflow (using command: conda remove tensorflow), then install 1.15.0 using command: conda install tensorflow=1.15.0. it works

This worked for me. Thanks.

**Comment by mikechen66** [comment]
The following lines of code do not work in the environment of TensorFlow 2.2 and Keras 2.4.3

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

or 

```
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
```

AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by kountaydwivedi** [comment]
> The solution provided by the Tensorflow team on their website:
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> doesn't seem to work either

This worked for me.
![image](https://user-images.githubusercontent.com/17232975/89093542-14e2e700-d3d9-11ea-8f13-f1c499d35271.png)

**Comment by bm777** [comment]
> Hi @cartal and @Kaarthic29, We will eventually update to tf2 but currently I am super busy with other stuff. The current and safest option is to use tf <2.0 for now. We will have a new release when we update it and also add trVAE.
> 
> Mo

Hi @M0hammadL 
Hope you are well.
I have this same issue with TensorFlow 2.1.0, I don't know if your finally found an alternative to use a placeholder in tf2 without disabling tf2.behavior

**Comment by DilipKarki** [comment]
The below worked for a similar problem i was facing. I tried going back to a previous version but couldn't. Now i have v2.3  working with the below:
1) Used upgrade script to change all my old files to v2 - https://www.tensorflow.org/guide/upgrade
2) After that there was still an issue which got fixed with this line (from suggestion few posts above here)
tf.compat.v1.disable_eager_execution()

**Comment by ParasGeeek** [comment]
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
It is working for me

**Comment by prataplyf** [comment]
It

> The solution provided by the Tensorflow team on their website:
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> doesn't seem to work either

Damm.... It works for me too, great

**Comment by alitokur** [comment]
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> works.
> I am using Python 3.7 and tensorflow 2.0.

its still working.

**Comment by Bryson582** [comment]
Can somebody help me?
`import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()`
It reminds me that I 

> WARNING:tensorflow:From /Users/brycelee/PycharmProjects/MNST/venv/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

And it tells me 'no module named compat'

**Comment by alitokur** [comment]
@Bryson582  which version of tensorflow do u use?

**Comment by Bryson582** [comment]
> @Bryson582 which version of tensorflow do u use?

tensorflow('2.3.1')

**Comment by Bryson582** [comment]
@alitokur tensorflow('2.3.1')

**Comment by Bryson582** [comment]
@alitokur I am using Python 2.7.16 and tensorflow '2.3.1'

**Comment by alitokur** [comment]
@Bryson582 may the problem be your python version? tensorflow2 requires python 3.5–3.8, pip and venv >= 19.0

**Comment by juiceboxjoe** [comment]
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

working with Python3.7 and TF 2.3.1

**Comment by monacv** [comment]
@mikechen66 AttributeError: module 'tensorflow' has no attribute 'compact'

**Comment by bm777** [comment]
> @mikechen66 AttributeError: module 'tensorflow' has no attribute 'compact'

Check if your TensorFlow is well installed on your machine.
try:
`import tensorflow`

**Comment by GP-Kulam** [comment]
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> works.
> I am using Python 3.7 and tensorflow 2.0.

hey, where to place this code snippet, can u please mention?

**Comment by alitokur** [comment]
@GP-Kulam you can use like the following on the import part:


```
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
```

**Comment by sshams514** [comment]
Hey I did that: 
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
but it does not work.
What else could be the problem?

**Comment by bm777** [comment]
Print the error here.

**Comment by sshams514** [comment]
@bm777: AttributeError: module 'tensorflow' has no attribute 'placeholder'

Thank you for your help!

**Comment by bm777** [comment]
For me, you have two choices if you are using TensorFlow 2.x:

1. use TensorFlow 2.x, by 
- `import tensorflow.compat.v1 as tf` and use tf in your code.
2. Remove your current version of TensorFlow, and install 1.x TensorFlow version.
`pip uninstall tensorflow
pip install tensorflow==1.7`

**Comment by sshams514** [comment]
@bm777 I tried that one too but I also use Keras in the code and for Keras tensorflow 2.2 is needed at least.
Is there another solution?

**Comment by bm777** [comment]
For better help, could you please, show a part of your code and plot the screenshot of your error here too.

**Comment by xtSumit** [comment]
> Hi,
> 
> Even I face the same AttributeError: module 'tensorflow' has no attribute 'placeholder' issue with tensorflow version 2.0
> 
> Any leads or workaround for this is greatly appreciated.
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
us tf.compat.v1.placeholder

**Comment by aditycahyap** [comment]
> The solution provided by the Tensorflow team on their website:
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> doesn't seem to work either

module 'tensorflow.compat.v1' has no attribute 'contrib'

**Comment by bm777** [comment]
You can choose to install another virtual env on your machine.
For my case, I use a separate virtual env for TensorFlow 2.3 and OpenCV 4.
`tf.contrib` has moved out of TF starting TF 2.0 alpha.

**Comment by noridayu1998** [comment]
> The following lines of code do not work in the environment of TensorFlow 2.2 and Keras 2.4.3
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior()
> ```
> 
> or
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.compat.v1.disable_eager_execution()
> ```
> 
> AttributeError: module 'tensorflow' has no attribute 'placeholder'
> 
> However, the following line code works effectively.
> 
> ```
> tf.compat.v1.placeholder()
> ```

i have used the tf.compat.v1.placeholder()
but it's not working. 
runfile('D:/1. PSM 2020/SEGMENTATION/pointnet-master/train.py', wdir='D:/1. PSM 2020/SEGMENTATION/pointnet-master')
Reloaded modules: provider, tf_util, pointnet_cls, transform_nets
Traceback (most recent call last):

  File "D:\1. PSM 2020\SEGMENTATION\pointnet-master\train.py", line 6, in <module>
    tf.compat.v1.placeholder()

TypeError: placeholder() missing 1 required positional argument: 'dtype'

**Comment by sonali90** [comment]
> 
> 
> The following lines of code do not work in the environment of TensorFlow 2.2 and Keras 2.4.3
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior()
> ```
> 
> or
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.compat.v1.disable_eager_execution()
> ```
> 
> AttributeError: module 'tensorflow' has no attribute 'placeholder'
> 
> However, the following line code works effectively.
> 
> ```
> tf.compat.v1.placeholder()
> ```

this is work for me...

**Comment by thatguyfig** [comment]
I wouldn't be surprised if TF are trying to phase out the use of v1 in v2 and hence are removing this submodule.

If you want to use v1 TF why install v2 and then use the v1 only features?????? It makes no sense.

**Comment by sigeek** [comment]
Hi! I still get the error with python 3.7.10 and tensorflow 2.4.1

**Comment by Rakeshkangal** [comment]
> > > ```
> > > import tensorflow.compat.v1 as tf
> > > tf.disable_v2_behavior() 
> > > ```
> > > 
> > > 
> > > works.
> > > I am using Python 3.7 and tensorflow 2.0.
> > 
> > 
> > yeah it is working now
> 
> for me its not working

how did you solve?

**Comment by Rakeshkangal** [comment]
> Hi guys,
> 
> I had to upgrade my `tensorflow` to re-install `diffxpy` and this seems to have broken my `scGen`: I've got the `AttributeError:` module 'tensorflow' has no attribute 'placeholder'`.
> 
> I'm trying to find a workaround this, but it seems that it's something that `scGen` will have to fix at some point? Do you have any recommendations?
> 
> Thanks in advance!

AttributeError: module 'tensorflow' has no attribute 'placeholder'
can any one please tell me how to solve this error message

**Comment by Rakeshkangal** [comment]
> > The solution provided by the Tensorflow team on their website:
> > ```
> > import tensorflow.compat.v1 as tf
> > tf.disable_v2_behavior() 
> > ```
> > 
> > 
> > doesn't seem to work either
> 
> module 'tensorflow.compat.v1' has no attribute 'contrib'

did you get?

**Comment by adamgayoso** [comment]
Hi everyone,

we updated scgen to use pytorch. you can install scgen from the master branch to use it. The documentation website also shows how to use this version. It will be released officially soon.

**Comment by 54wb** [comment]
> For me, you have two choices if you are using TensorFlow 2.x:
> 
> 1. use TensorFlow 2.x, by
> 
> * `import tensorflow.compat.v1 as tf` and use tf in your code.
> 
> 1. Remove your current version of TensorFlow, and install 1.x TensorFlow version.
>    `pip uninstall tensorflow pip install tensorflow==1.7`

works well!  Thank you

**Comment by bm777** [comment]
@54wb Happy to hear it :)

**Comment by ChlaegerIO** [comment]
> > For me, you have two choices if you are using TensorFlow 2.x:
> > 
> > 1. use TensorFlow 2.x, by
> > 
> > 
> > * `import tensorflow.compat.v1 as tf` and use tf in your code.
> > 
> > 
> > 1. Remove your current version of TensorFlow, and install 1.x TensorFlow version.
> >    `pip uninstall tensorflow pip install tensorflow==1.7`
> 
> works well! Thank you

I am using TensorFlow 2.7 and for me this doesn't work. I use python 3.9.x in my virtual environment. I have tried to install also different tensorflow 1.x version, but that's not possible.

**Comment by Purvapatil2001** [comment]
> > > For me, you have two choices if you are using TensorFlow 2.x:
> > > 
> > > 1. use TensorFlow 2.x, by
> > > 
> > > 
> > > * `import tensorflow.compat.v1 as tf` and use tf in your code.
> > > 
> > > 
> > > 1. Remove your current version of TensorFlow, and install 1.x TensorFlow version.
> > >    `pip uninstall tensorflow pip install tensorflow==1.7`
> > 
> > 
> > works well! Thank you
> 
> I am using TensorFlow 2.7 and for me this doesn't work. I use python 3.9.x in my virtual environment. I have tried to install also different tensorflow 1.x version, but that's not possible.
> 
> ```
> pip install tensorflow==1.7
> ERROR: Could not find a version that satisfies the requirement tensorflow==1.7 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
> ERROR: No matching distribution found for tensorflow==1.7
> ```

same problem...
please help !!!

**Comment by rpsipl2021** [comment]
> 

this is working.

**Comment by samkml** [comment]
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
> ```
> 
> works. I am using Python 3.7 and tensorflow 2.0.

This works for python 11 and tesorflow 2.12 too

**Comment by samkml** [comment]
> The solution provided by the Tensorflow team on their website:
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior() 
This works for python 11 and tesorflow 2.12 too
