### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by anjugopinath** [theislab/scgen#37]
loss.py", line 209, in getRealObservables
    loadRealObservs = tf.placeholder(tf.bool, name='OBSERVS_GATE')
AttributeError: module 'tensorflow' has no attribute 'placeholder'

OS: Ubuntu
Tensorflow Version : 1.15
python version :  3.6.1

**Comment by anjugopinath** [comment]
Is it possible to get it working with TF version 1.15?

**Comment by M0hammadL** [comment]
Hi we released the new pytorch version please use this new version.

Mo
